// Gujarat FIRs. 20 varied standalone records across 14 districts, the planted cluster-D
// gang (with one FIR across the border in Rajasthan), its decoy and control, and the
// Navrangpura PS records that give the home station a visible trend.
// Section numbers under Gujarat state Acts are illustrative: verify before presenting.

export const GUJARAT_STATIONS = {
  navrangpura: { ps: 'Navrangpura', district: 'Ahmedabad City', state: 'Gujarat', lat: 23.036, lng: 72.561, code: '24191021' },
  sghighway: { ps: 'Sarkhej', district: 'Ahmedabad City', state: 'Gujarat', lat: 22.991, lng: 72.501, code: '24191034' },
  varachha: { ps: 'Varachha', district: 'Surat City', state: 'Gujarat', lat: 21.209, lng: 72.857, code: '24225012' },
  salabatpura: { ps: 'Salabatpura', district: 'Surat City', state: 'Gujarat', lat: 21.189, lng: 72.838, code: '24225019' },
  sayajigunj: { ps: 'Sayajigunj', district: 'Vadodara City', state: 'Gujarat', lat: 22.311, lng: 73.181, code: '24229008' },
  rajkot: { ps: 'Rajkot A Division', district: 'Rajkot City', state: 'Gujarat', lat: 22.297, lng: 70.799, code: '24222001' },
  gandhidham: { ps: 'Gandhidham A Division', district: 'Kutch East', state: 'Gujarat', lat: 23.075, lng: 70.133, code: '24207003' },
  bhuj: { ps: 'Bhuj City A Division', district: 'Kutch West', state: 'Gujarat', lat: 23.242, lng: 69.667, code: '24208001' },
  bhavnagar: { ps: 'Alang Marine', district: 'Bhavnagar', state: 'Gujarat', lat: 21.412, lng: 72.201, code: '24198017' },
  jamnagar: { ps: 'Jamnagar City A Division', district: 'Jamnagar', state: 'Gujarat', lat: 22.471, lng: 70.058, code: '24203001' },
  mehsana: { ps: 'Mehsana City A Division', district: 'Mehsana', state: 'Gujarat', lat: 23.588, lng: 72.369, code: '24212001' },
  palanpur: { ps: 'Palanpur Taluka', district: 'Banaskantha', state: 'Gujarat', lat: 24.172, lng: 72.438, code: '24196009' },
  vapi: { ps: 'Vapi GIDC', district: 'Valsad', state: 'Gujarat', lat: 20.372, lng: 72.905, code: '24230006' },
  gandhinagar: { ps: 'Sector 7', district: 'Gandhinagar', state: 'Gujarat', lat: 23.216, lng: 72.641, code: '24201004' },
  anand: { ps: 'Anand Town', district: 'Anand', state: 'Gujarat', lat: 22.556, lng: 72.951, code: '24193001' },
  udaipur: { ps: 'Hathipole', district: 'Udaipur', state: 'Rajasthan', lat: 24.585, lng: 73.691, code: '08332006' },
  dahod: { ps: 'Dahod Town', district: 'Dahod', state: 'Gujarat', lat: 22.837, lng: 74.255, code: '24199001' },
}

// Placeholder officer names supplied by the project owner.
const OFFICERS = ['Nandan', 'Divya', 'Anvika', 'Adhira']
export const GUJARAT_IO = {
  ...Object.fromEntries(Object.keys(GUJARAT_STATIONS).map((k, i) => [k, [[OFFICERS[i % OFFICERS.length], 'Police Sub-Inspector']]])),
  // home station of the demo personas: two investigating officers
  navrangpura: [['Bhargav', 'Police Sub-Inspector'], ['Nandan', 'Police Sub-Inspector']],
}

export const GUJARAT_SECTIONS = {
  prohib65: 'Gujarat Prohibition Act 65(e) - Import, transport or possession of liquor',
  prohib98: 'Gujarat Prohibition Act 98(2) - Vehicle used for carrying liquor',
  landGrab: 'Gujarat Land Grabbing (Prohibition) Act 4 - Land grabbing',
  moneyLend: 'Gujarat Money-Lenders Act 40 - Money lending without licence',
  emigration: 'Emigration Act 24 - Recruiting for emigration without registration',
  ndps22: 'NDPS Act 22 - Possession of psychotropic substances',
  ndps8c: 'NDPS Act 8(c) - Prohibited dealing in narcotic drugs',
}

const acc = (name, relative_name = '', address = '') => ({ name, relative_name, address })
const UNKNOWN = acc('Unknown')

export const gujaratRaw = (S) => [
  ['standalone', 'navrangpura', '2026-06-05', 4, 'Pahar 4 (12:00-15:00 hrs)', 'Online, complainant at C.G. Road, Navrangpura',
    [S.cheat, S.it66d, S.common],
    'Ketan Shah', [UNKNOWN],
    ['Male', '46-60', 'Stranger'],
    'Complainant was added to a WhatsApp group offering stock tips and was told to install a trading app. The app showed large profits, and he deposited Rs 27,40,000 in eleven transactions for IPO allotment. Withdrawal was refused unless he paid a further 30 percent tax.',
    'en', 'Victim added to a WhatsApp group with stock tips, induced to install a fake trading app showing false profits, then asked for more money before withdrawal.',
    'Under investigation, bank accounts frozen'],
  ['standalone', 'navrangpura', '2026-08-13', 0, 'Pahar 8 (00:00-03:00 hrs)', 'Commercial complex, Ashram Road, Ahmedabad',
    [S.cheat, S.personation, S.it66c, S.it66d, S.common],
    'PSI Nandan (on behalf of State)', [acc('Dhaval Parmar', '', 'Naroda, Ahmedabad'), acc('Rishabh Jain', '', 'Maninagar, Ahmedabad')],
    ['Not applicable', 'Not applicable', 'Stranger'],
    'On secret information a raid was conducted at night on an office running a call centre. Fourteen persons were found making internet calls to foreign nationals, posing as officers of a tax department and demanding payment through gift cards. 22 computers, scripts and lead sheets seized.',
    'en', 'Illegal call centre calling foreign nationals at night, posing as tax officers and collecting payment through gift cards.',
    'Accused arrested, devices sent to FSL'],
  ['standalone', 'sghighway', '2026-04-18', 0, 'Pahar 8 (00:00-03:00 hrs)', 'S.G. Highway near Sarkhej crossing',
    [S.rash, S.negligence],
    'Mitesh Rabari', [acc('Driver of car GJ-01-XXXX (name not known)')],
    ['Male', '18-30', 'Stranger'],
    'A car driven at very high speed on the highway hit two persons on a scooter from behind at about 1 am and fled. The pillion rider died on the spot and the rider is under treatment.',
    'en', 'Speeding car hit a scooter from behind on the highway at night and fled; one person died.',
    'Vehicle identified from CCTV, driver absconding'],
  ['standalone', 'varachha', '2026-07-12', 0, 'Pahar 6 (18:00-21:00 hrs)', 'Mini Bazar, Varachha, Surat',
    [S.theft],
    'Bhavesh Kakadiya', [UNKNOWN],
    ['Male', '31-45', 'Stranger'],
    'તા. 12/07/2026 ના રોજ સાંજે ફરિયાદીએ પોતાની મોટરસાઇકલ વરાછા મિની બજાર પાસે પાર્ક કરી હતી. અડધા કલાક પછી પરત આવતાં મોટરસાઇકલ જોવા મળી ન હતી. કોઈ અજાણ્યો ઇસમ હેન્ડલ લોક તોડી ચોરી કરી લઈ ગયો છે.',
    'gu', 'Motorcycle parked near the market in the evening was stolen by breaking the handle lock.',
    'Under investigation'],
  ['standalone', 'varachha', '2026-03-11', 0, 'Pahar 6 (18:00-21:00 hrs)', 'Near Hirabaug circle, Varachha, Surat',
    [S.robbery, S.hurtWeapon, S.arms, S.common],
    'Employee of an angadia firm', [UNKNOWN, UNKNOWN, UNKNOWN],
    ['Male', '31-45', 'Stranger'],
    'Complainant, an angadia firm employee carrying polished diamonds worth Rs 1.8 crore, was intercepted in the evening by three persons on two bikes. One pointed a pistol, another hit him on the head, and they took the bag and fled towards Kamrej.',
    'en', 'Three men on two bikes intercepted an angadia courier in the evening, threatened him with a pistol and robbed a bag of diamonds.',
    'Under investigation'],
  ['standalone', 'salabatpura', '2026-05-27', 6, 'Pahar 4 (12:00-15:00 hrs)', 'Textile market, Ring Road, Surat',
    [S.cbt, S.cheat],
    'Proprietor, textile trading firm', [acc('Naresh Agarwal', '', 'Reportedly of Jaipur, Rajasthan')],
    ['Not applicable', 'Not applicable', 'Business contact'],
    'Accused purchased grey cloth worth Rs 64 lakh on credit over three months through a broker, paid the first two bills to win trust, then closed his shop and left without paying the remaining amount.',
    'en', 'Trader bought cloth on credit, paid early bills to win trust, then closed the shop and left without paying.',
    'Under investigation'],
  ['standalone', 'sayajigunj', '2026-06-03', 0, 'Pahar 2 (06:00-09:00 hrs)', 'Near Kamatibaug gate, Sayajigunj, Vadodara',
    [S.snatch],
    'Hansaben Patel', [UNKNOWN, UNKNOWN],
    ['Female', '60+', 'Stranger'],
    'તા. 03/06/2026 ના રોજ સવારે ફરિયાદી મંદિરેથી ઘરે પરત ફરી રહ્યા હતા ત્યારે બાઇક પર આવેલા બે અજાણ્યા ઇસમોએ ગળામાંથી સોનાની ચેઇન ઝૂંટવી લીધી અને ફતેગંજ તરફ ભાગી ગયા. ફરિયાદી વૃદ્ધ હોઈ પડી જતાં ઘૂંટણમાં ઈજા થઈ છે.',
    'gu', 'Two unknown men on a bike snatched a gold chain from an elderly woman returning from the temple in the morning.',
    'Under investigation'],
  ['standalone', 'sayajigunj', '2026-02-24', 1, 'Pahar 5 (15:00-18:00 hrs)', 'Near railway station, Sayajigunj, Vadodara',
    [S.kidnap],
    'Ramilaben Vasava', [UNKNOWN],
    ['Male', 'Under 18', 'Stranger'],
    'Complainant’s 9 year old son was playing outside the railway station while she was selling goods. He went missing in the afternoon. CCTV shows an unknown woman leading him towards the platform.',
    'en', 'Child playing outside the railway station led away by an unknown woman in the afternoon.',
    'Child recovered at Bharuch, accused arrested'],
  ['standalone', 'rajkot', '2026-07-30', 0, 'Pahar 1 (03:00-06:00 hrs)', 'Ahmedabad highway near Kuvadva, Rajkot',
    [S.prohib65, S.prohib98, S.common],
    'PSI Divya (on behalf of State)', [acc('Mukesh Bishnoi', '', 'Sanchore, Rajasthan'), acc('Jagdish Vaghela', '', 'Rajkot')],
    ['Not applicable', 'Not applicable', 'Stranger'],
    'During vehicle checking before dawn a truck carrying cattle feed bags was stopped on the highway. On search, 412 boxes of IMFL whisky and beer were found hidden under the bags. Driver and cleaner detained.',
    'en', 'Truck stopped on the highway before dawn; boxes of liquor found hidden under cattle feed bags.',
    'Accused arrested, vehicle seized'],
  ['standalone', 'rajkot', '2026-05-09', 2, 'Pahar 5 (15:00-18:00 hrs)', 'Gondal Road, Rajkot',
    [S.moneyLend, S.extortion, S.intimidation],
    'Jayesh Dobariya', [acc('Bharat Boricha', '', 'Gondal Road, Rajkot')],
    ['Male', '31-45', 'Acquaintance'],
    'Complainant borrowed Rs 5 lakh at 10 percent monthly interest from the accused, a moneylender without licence. Though he has repaid Rs 9 lakh, the accused took signed blank cheques and threatened to take over his shop.',
    'en', 'Unlicensed moneylender charged very high interest, took signed blank cheques and threatened to take over the shop.',
    'Under investigation'],
  ['standalone', 'gandhidham', '2026-08-06', 0, 'Pahar 3 (09:00-12:00 hrs)', 'Container freight station near Kandla port',
    [S.ndps8c, S.ndps22, S.ndps29],
    'Officer of a central agency (on behalf of State)', [acc('Proprietor of an importing firm (name withheld)')],
    ['Not applicable', 'Not applicable', 'Stranger'],
    'A container declared as gypsum powder was examined on specific intelligence. 38 kg of methamphetamine was found concealed inside false-bottom bags. The importing firm’s address was found to be bogus.',
    'en', 'Synthetic drug concealed inside bags in an imported container declared as gypsum powder; importer address bogus.',
    'Under investigation'],
  ['standalone', 'bhuj', '2026-06-21', 1, 'Pahar 3 (09:00-12:00 hrs)', 'ATM kiosk, Station Road, Bhuj',
    [S.cheat, S.theft],
    'Karsanbhai Ahir', [UNKNOWN],
    ['Male', '60+', 'Stranger'],
    'Complainant, a retired farmer, could not operate the ATM. An unknown person offered help, watched the PIN and swapped his card with a similar one. Rs 80,000 was withdrawn from another ATM within an hour.',
    'en', 'Unknown person offered help at the ATM to an elderly man, watched the PIN, swapped the card and withdrew money.',
    'Under investigation'],
  ['standalone', 'bhavnagar', '2026-03-26', 0, 'Pahar 8 (00:00-03:00 hrs)', 'Plot 84, Alang ship-breaking yard',
    [S.theft, S.common],
    'Yard manager', [acc('Imtiyaz Sheikh', '', 'Trapaj, Bhavnagar'), acc('Vijay Baraiya', '', 'Alang, Bhavnagar')],
    ['Not applicable', 'Not applicable', 'Former employee'],
    'Security guard caught two persons at night loading copper cable and brass fittings from a dismantled ship into a tempo. About 600 kg of material recovered.',
    'en', 'Copper cable and brass fittings stolen from a ship-breaking yard at night and loaded into a tempo.',
    'Accused arrested'],
  ['standalone', 'jamnagar', '2026-04-02', 9, 'Pahar 4 (12:00-15:00 hrs)', 'Survey land near Lalpur bypass, Jamnagar',
    [S.landGrab, S.forgery, S.intimidation],
    'Rekhaben Nanda', [acc('Pravinsinh Jadeja', '', 'Jamnagar')],
    ['Female', '60+', 'Stranger'],
    'Complainant, a widow living in Mumbai, found that the accused had taken possession of her agricultural land, built a compound wall and prepared a forged power of attorney. When she objected she was threatened.',
    'en', 'Accused took possession of an absent owner’s land using a forged power of attorney and threatened her.',
    'Under investigation'],
  ['standalone', 'mehsana', '2026-07-03', 5, 'Pahar 4 (12:00-15:00 hrs)', 'Office near Modhera crossing, Mehsana',
    [S.emigration, S.cheat, S.forgery],
    'Alpesh Chaudhary', [acc('Hitesh Patel @ Bobby', '', 'Kalol, Gandhinagar')],
    ['Male', '18-30', 'Acquaintance'],
    'Accused, working as an unregistered agent, took Rs 42 lakh promising to send the complainant and his wife abroad. He gave them a fake visa and bogus bank statements. They were sent back from a transit airport.',
    'en', 'Unregistered agent took money to send a couple abroad and supplied a fake visa and bogus documents.',
    'Under investigation'],
  ['standalone', 'palanpur', '2026-05-15', 0, 'Pahar 8 (00:00-03:00 hrs)', 'NH-27 near Chandisar, Palanpur',
    [S.robbery, S.restraint, S.common],
    'Truck driver', [UNKNOWN, UNKNOWN, UNKNOWN, UNKNOWN],
    ['Male', '31-45', 'Stranger'],
    'Four persons in a car overtook the complainant’s truck carrying cumin seed on the highway at night, tied up the driver and cleaner, and drove the truck away. The empty truck was found 40 km away.',
    'en', 'Four men in a car stopped a truck on the highway at night, tied up the driver and took the goods.',
    'Under investigation'],
  ['standalone', 'vapi', '2026-06-14', 1, 'Pahar 8 (00:00-03:00 hrs)', 'Chemical unit, Phase 2, Vapi GIDC',
    [S.hbNight, S.theft],
    'Factory manager', [UNKNOWN],
    ['Not applicable', 'Not applicable', 'Stranger'],
    'During the weekly shutdown the store room shutter of the factory was broken at night. Palladium catalyst worth Rs 22 lakh was stolen. Only someone who knew its value and location could have done this.',
    'en', 'Factory store room shutter broken at night during weekly shutdown; costly catalyst stolen, insider knowledge suspected.',
    'Under investigation'],
  ['standalone', 'gandhinagar', '2026-02-09', 3, 'Pahar 4 (12:00-15:00 hrs)', 'Sector 7, Gandhinagar',
    [S.cheat, S.forgery, S.personation],
    'Nikunj Trivedi', [acc('Sanjay Mahida', '', 'Sector 24, Gandhinagar')],
    ['Male', '18-30', 'Acquaintance'],
    'Accused, posing as a personal assistant in the secretariat, took Rs 12 lakh from the complainant and four others promising clerk jobs, and gave them forged appointment letters.',
    'en', 'Accused posing as a secretariat assistant took money for government jobs and issued forged appointment letters.',
    'Accused arrested'],
  ['standalone', 'anand', '2026-04-29', 12, 'Pahar 4 (12:00-15:00 hrs)', 'Sub-registrar office, Anand',
    [S.forgery, S.cheat, S.personation, S.common],
    'Power of attorney holder of an NRI owner', [acc('Ghanshyam Thakor', '', 'Karamsad, Anand'), acc('Unknown woman impersonating the owner')],
    ['Female', '60+', 'Stranger'],
    'A house belonging to an NRI woman living abroad was sold by producing another woman posing as the owner before the sub-registrar, with a forged identity card. The sale deed was registered for Rs 85 lakh.',
    'en', 'House of an NRI owner sold by producing an impostor posing as the owner with a forged identity card.',
    'Under investigation'],
  ['standalone', 'dahod', '2026-08-24', 0, 'Pahar 5 (15:00-18:00 hrs)', 'Village near Dahod town',
    [S.riot, S.hurtWeapon, S.mischief],
    'Ramsingbhai Damor', [acc('Kalubhai Bhabhor', '', 'Dahod'), acc('Shankar Bhabhor', '', 'Dahod')],
    ['Male', '46-60', 'Relative'],
    'Due to a dispute over the boundary of farm land, a group of about ten persons led by the accused attacked the complainant’s family with sticks and a sword and damaged the standing crop.',
    'en', 'Group attacked a family with sticks and a sword over a farm boundary dispute and damaged the crop.',
    'Under investigation'],
  // ---------- Cluster D: follow from bank, break car glass, lift cash bag ----------
  ['cluster-D', 'navrangpura', '2026-04-08', 0, 'Pahar 4 (12:00-15:00 hrs)', 'Outside a restaurant, C.G. Road, Navrangpura',
    [S.theft, S.mischief, S.common],
    'Paresh Shah', [acc('Vikram Solanki @ Vicky', '', 'Address not known'), UNKNOWN],
    ['Male', '46-60', 'Stranger'],
    'Complainant withdrew Rs 6,50,000 cash from the bank and kept the bag on the rear seat of his car. He parked outside a restaurant in the afternoon and went in for lunch. On return the rear window glass was broken and the cash bag was missing. CCTV shows two men on a motorcycle who had followed the car from the bank. One is identified as Vikram Solanki alias Vicky.',
    'en', 'Victim followed from the bank after withdrawing cash; rear window glass of the parked car broken in the afternoon and the cash bag lifted by two men on a motorcycle.',
    'Under investigation', 0],
  ['cluster-D', 'salabatpura', '2026-05-19', 0, 'Pahar 4 (12:00-15:00 hrs)', 'Ring Road near textile market, Surat',
    [S.theft, S.mischief, S.common],
    'Rajesh Jariwala', [acc('Vikrambhai Solanki', '', 'Reportedly of Ahmedabad'), UNKNOWN],
    ['Male', '31-45', 'Stranger'],
    'Complainant, a textile trader, withdrew Rs 4,20,000 from the bank for wage payment and parked his car near the market in the afternoon. Within ten minutes the side window glass was broken and the bag with cash taken. Two persons on a motorcycle were seen following him from the bank. Fingerprint on the door matched Vikrambhai Solanki.',
    'en', 'Trader followed from the bank after cash withdrawal; side window glass of the parked car broken in the afternoon and the cash bag taken by two persons on a motorcycle.',
    'Under investigation'],
  ['cluster-D', 'sayajigunj', '2026-06-23', 0, 'Pahar 4 (12:00-15:00 hrs)', 'Near Sayajigunj bank branch, Vadodara',
    [S.theft, S.mischief],
    'Dipakbhai Amin', [acc('V. Solanki', '', 'Address not known'), UNKNOWN],
    ['Male', '60+', 'Stranger'],
    'તા. 23/06/2026 ના રોજ બપોરે ફરિયાદીએ બેંકમાંથી રૂ. 3,00,000 રોકડા ઉપાડી થેલો પોતાની કારમાં મૂક્યો હતો. કાર પાર્ક કરી દવા લેવા ગયા ત્યારે બાઇક પર આવેલા બે ઇસમોએ કારનો કાચ તોડી રોકડનો થેલો ચોરી લીધો. CCTV માં બંને ઇસમો બેંકથી પીછો કરતા દેખાય છે. એક ઇસમની ઓળખ V. Solanki ઉર્ફે વિકી તરીકે થઈ છે.',
    'gu', 'Elderly victim followed from the bank after withdrawing cash; window glass of the parked car broken in the afternoon and the cash bag stolen by two men on a motorcycle.',
    'Under investigation'],
  ['cluster-D', 'rajkot', '2026-07-28', 0, 'Pahar 4 (12:00-15:00 hrs)', 'Yagnik Road, Rajkot',
    [S.theft, S.mischief, S.common],
    'Hiren Kotecha', [acc('Vikramsinh Solanky @ Vicky', '', 'Ahmedabad'), acc('Dinesh Makwana', '', 'Address not known')],
    ['Male', '31-45', 'Stranger'],
    'Complainant withdrew Rs 8,00,000 cash from the bank and parked his car on Yagnik Road in the afternoon. The accused, who followed him from the bank on a motorcycle, broke the front window glass with a catapult and steel ball and lifted the cash bag. Both are seen in CCTV footage.',
    'en', 'Victim followed from the bank after withdrawing cash; window glass of the parked car broken with a catapult in the afternoon and the cash bag lifted by two men on a motorcycle.',
    'Under investigation'],
  ['cluster-D', 'udaipur', '2026-08-18', 0, 'Pahar 4 (12:00-15:00 hrs)', 'Near Delhi Gate, Udaipur',
    [S.theft, S.mischief, S.common],
    'Mahendra Jain', [acc('Vikram Solanki', '', 'Ahmedabad, Gujarat'), acc('Dinesh Makwana', '', 'Ahmedabad, Gujarat')],
    ['Male', '46-60', 'Stranger'],
    'Complainant withdrew Rs 5,00,000 from the bank and parked his car near Delhi Gate in the afternoon. Two men on a motorcycle who followed him from the bank broke the window glass and took the cash bag. Traffic police caught both accused at a checkpoint with the bag, a catapult and steel balls.',
    'en', 'Victim followed from the bank after cash withdrawal; window glass of the parked car broken in the afternoon and the cash bag taken; accused caught on a motorcycle with a catapult.',
    'Accused arrested, property recovered'],

  // ---------- Same method, different accused ----------
  ['decoy', 'gandhinagar', '2026-07-14', 0, 'Pahar 4 (12:00-15:00 hrs)', 'Sector 11 market, Gandhinagar',
    [S.theft, S.mischief],
    'Bharatbhai Prajapati', [acc('Mahesh Thakor', '', 'Dehgam, Gandhinagar')],
    ['Male', '46-60', 'Stranger'],
    'Complainant withdrew Rs 2,50,000 cash from the bank and parked his car at the market in the afternoon. The window glass was broken and the cash bag stolen. Accused Mahesh Thakor, who followed him from the bank on a motorcycle, was caught by the public.',
    'en', 'Victim followed from the bank after withdrawing cash; window glass of the parked car broken in the afternoon and the cash bag stolen by a man on a motorcycle.',
    'Accused arrested'],

  // ---------- Same name, unrelated offence ----------
  ['control', 'bhavnagar', '2025-01-16', 3, 'Pahar 5 (15:00-18:00 hrs)', 'Alang yard office, Bhavnagar',
    [S.cbt],
    'Partner of a scrap trading firm', [acc('Vikram Solanki', 'Jethabhai Solanki (father)', 'Talaja, Bhavnagar')],
    ['Not applicable', 'Not applicable', 'Employee'],
    'Accused, employed as a cashier, did not deposit sale proceeds of Rs 3,40,000 collected from customers over two months and stopped coming to work.',
    'en', 'Cashier collected sale proceeds from customers and did not deposit them with the firm.',
    'Charge sheet filed'],

  // ---------- Navrangpura PS: home station for the trend demo ----------
  ['standalone', 'navrangpura', '2025-12-14', 0, 'Pahar 6 (18:00-21:00 hrs)', 'Municipal Market parking, C.G. Road',
    [S.theft],
    'Jignesh Modi', [UNKNOWN],
    ['Male', '18-30', 'Stranger'],
    'Complainant parked his scooter at the market parking in the evening. When he returned after shopping the scooter was missing.',
    'en', 'Scooter parked at the market parking stolen in the evening.',
    'Under investigation', 1],
  ['standalone', 'navrangpura', '2026-02-02', 2, 'Pahar 4 (12:00-15:00 hrs)', 'Residential society, Navrangpura',
    [S.dwelling],
    'Shilpaben Desai', [acc('Kamlesh Damor', '', 'Address not known')],
    ['Female', '60+', 'Domestic help'],
    'Complainant, a senior citizen living alone, found gold bangles and Rs 45,000 missing from her cupboard. The accused, employed as a cook for two months, has not come to work since and his phone is switched off.',
    'en', 'Domestic help employed by an elderly woman stole gold bangles and cash from the cupboard and disappeared.',
    'Under investigation', 1],
  ['standalone', 'navrangpura', '2026-03-20', 0, 'Pahar 7 (21:00-24:00 hrs)', 'Outside a cafe near the university',
    [S.hurt, S.intimidation, S.common],
    'Yash Rathod', [acc('Parth Chauhan', '', 'Naranpura, Ahmedabad'), acc('Meet Vyas', '', 'Naranpura, Ahmedabad')],
    ['Male', '18-30', 'Acquaintance'],
    'After an argument over a parking space at night, the accused slapped the complainant, hit him with a helmet and threatened him.',
    'en', 'Argument over a parking space at night; accused hit the complainant with a helmet and threatened him.',
    'Charge sheet filed', 1],
  ['standalone', 'navrangpura', '2026-07-09', 0, 'Pahar 6 (18:00-21:00 hrs)', 'Law Garden parking',
    [S.theft],
    'Komal Bhatt', [UNKNOWN],
    ['Female', '18-30', 'Stranger'],
    'Complainant parked her scooter at the Law Garden parking in the evening and went to the food stalls. On return the scooter was missing.',
    'en', 'Scooter parked at the garden parking stolen in the evening.',
    'Under investigation', 1],
  ['standalone', 'navrangpura', '2026-08-03', 0, 'Pahar 6 (18:00-21:00 hrs)', 'Law Garden parking',
    [S.theft],
    'Darshan Panchal', [UNKNOWN],
    ['Male', '18-30', 'Stranger'],
    'Motorcycle parked at the Law Garden parking in the evening was stolen. The handle lock was engaged.',
    'en', 'Motorcycle parked at the garden parking stolen in the evening by breaking the handle lock.',
    'Under investigation', 1],
  ['standalone', 'navrangpura', '2026-08-22', 0, 'Pahar 6 (18:00-21:00 hrs)', 'Law Garden parking',
    [S.theft],
    'Foram Joshi', [UNKNOWN],
    ['Female', '31-45', 'Stranger'],
    'Complainant found her scooter missing from the Law Garden parking in the evening. This is the third vehicle theft reported from the same parking in two months.',
    'en', 'Scooter parked at the garden parking stolen in the evening.',
    'Under investigation', 1],
]
