"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { BriefPlanResponse } from "@/lib/types";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/** Render the plan into a light-theme, inline-styled HTML email. */
function planToHtml(plan: BriefPlanResponse): string {
  const rows = plan.zones
    .map((z) => {
      const delta =
        z.delta > 0 ? `+${z.delta}` : z.delta < 0 ? String(z.delta) : "—";
      return `<tr>
        <td style="padding:8px 10px;border-bottom:1px solid #e5e7eb;font-weight:600">#${z.rank}</td>
        <td style="padding:8px 10px;border-bottom:1px solid #e5e7eb">${esc(z.name ?? z.h3_r8)}</td>
        <td style="padding:8px 10px;border-bottom:1px solid #e5e7eb;text-align:right">${Math.round(z.probability * 100)}%</td>
        <td style="padding:8px 10px;border-bottom:1px solid #e5e7eb;text-align:center">${z.current_units} &rarr; ${z.suggested_units} (${delta})</td>
        <td style="padding:8px 10px;border-bottom:1px solid #e5e7eb">${esc(z.peak_window ?? "—")}</td>
      </tr>`;
    })
    .join("");

  const spikes = plan.spikes.length
    ? "<ul style='margin:8px 0 0;padding-left:18px;color:#374151'>" +
      plan.spikes
        .slice(0, 6)
        .map(
          (s) =>
            `<li style="margin:3px 0">${esc(s.crime_type)} in ${esc(
              s.name ?? s.h3_r8
            )} — ${s.recent} vs ${s.baseline} baseline${
              s.reason ? ` (${esc(s.reason)})` : ""
            }</li>`
        )
        .join("") +
      "</ul>"
    : "<p style='color:#6b7280;margin:8px 0 0'>No unusual spikes this week.</p>";

  return `<!doctype html><html><body style="margin:0;background:#f3f4f6;padding:24px;font-family:Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#111827">
  <div style="max-width:640px;margin:0 auto;background:#ffffff;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden">
    <div style="background:#1b3a6b;color:#ffffff;padding:16px 20px">
      <div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;opacity:.85">Netra · Crime Intelligence</div>
      <div style="font-size:20px;font-weight:800;margin-top:2px">Weekly Patrol Brief — ${esc(plan.district)}</div>
      <div style="font-size:13px;opacity:.9;margin-top:4px">Week of ${esc(plan.week_start)} – ${esc(plan.week_end)} · data up to ${esc(plan.ref_date)}</div>
    </div>
    <div style="padding:20px">
      <div style="background:#fffbeb;border:1px solid #fde68a;color:#92400e;border-radius:8px;padding:8px 12px;font-size:12.5px;font-weight:600;margin-bottom:16px">
        Decision support — for SHO review and approval. Not an automated order.
      </div>
      <p style="font-size:14px;line-height:1.6;color:#374151;margin:0 0 16px">${esc(plan.summary)}</p>
      <div style="font-size:13px;color:#6b7280;margin-bottom:6px">
        <b>${plan.total_units}</b> units available · <b>${plan.allocated_units}</b> placed · <b>${plan.reserve_units}</b> in reserve
      </div>
      <table style="width:100%;border-collapse:collapse;font-size:13px;margin-top:6px">
        <thead><tr style="background:#f9fafb;text-align:left;color:#6b7280;font-size:11px;text-transform:uppercase">
          <th style="padding:8px 10px">#</th><th style="padding:8px 10px">Zone</th>
          <th style="padding:8px 10px;text-align:right">Risk</th>
          <th style="padding:8px 10px;text-align:center">Units</th>
          <th style="padding:8px 10px">Be there</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <div style="font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:#6b7280;margin-top:18px;font-weight:700">Spike alerts</div>
      ${spikes}
      <p style="font-size:11px;color:#9ca3af;margin-top:20px;border-top:1px solid #e5e7eb;padding-top:12px">
        Generated by Netra at ${esc(plan.generated_at)}. Netra recommends; the SHO decides.
      </p>
    </div>
  </div></body></html>`;
}

function planToText(plan: BriefPlanResponse): string {
  const lines = [
    `Weekly Patrol Brief — ${plan.district}`,
    `Week of ${plan.week_start} – ${plan.week_end}`,
    "",
    plan.summary,
    "",
    ...plan.zones.map(
      (z) =>
        `#${z.rank} ${z.name ?? z.h3_r8} — ${Math.round(
          z.probability * 100
        )}% · ${z.current_units}->${z.suggested_units} units · ${z.peak_window ?? "—"}`
    ),
    "",
    "Decision support — for SHO review and approval. Not an automated order.",
  ];
  return lines.join("\n");
}

export default function EmailBriefButton({ plan }: { plan: BriefPlanResponse }) {
  const [open, setOpen] = useState(false);
  const [to, setTo] = useState("");
  // the station's usual recipient (EMAIL_DEFAULT_TO on the server); when set,
  // the Email button sends straight to it without asking
  const [defaultTo, setDefaultTo] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState<{ ok: boolean; text: string } | null>(null);

  useEffect(() => {
    api.emailStatus().then(
      (s) => setDefaultTo(s.default_to),
      () => {}
    );
  }, []);

  async function send(recipient: string) {
    setBusy(true);
    setMsg(null);
    try {
      const res = await api.emailBrief({
        to: recipient,
        subject: `Netra — patrol brief · ${plan.district} · week of ${plan.week_start}`,
        html: planToHtml(plan),
        text: planToText(plan),
      });
      if (res.ok) {
        setMsg({ ok: true, text: `Sent to ${recipient}` });
        setOpen(false);
        setTimeout(() => setMsg((m) => (m?.ok ? null : m)), 5000);
      } else if (!res.configured) {
        setMsg({
          ok: false,
          text: "Email not configured yet — add RESEND_API_KEY on the server.",
        });
      } else {
        setMsg({ ok: false, text: res.error ?? "Could not send." });
      }
    } catch {
      setMsg({ ok: false, text: "Could not reach the server." });
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="relative">
      <button
        onClick={() => (defaultTo ? send(defaultTo) : setOpen((v) => !v))}
        disabled={busy}
        className="btn-ghost"
        aria-expanded={defaultTo ? undefined : open}
        title={defaultTo ? `Email this brief to ${defaultTo}` : "Email this brief"}
      >
        <svg width="15" height="15" viewBox="0 0 16 16" fill="none">
          <rect x="1.5" y="3" width="13" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.4" />
          <path d="M2 4l6 4.5L14 4" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
        {busy && defaultTo ? "Sending…" : "Email"}
      </button>

      {/* result of a direct send */}
      {defaultTo && msg && (
        <div
          role="status"
          className={`absolute right-0 top-full z-40 mt-2 w-max max-w-xs animate-pop-in rounded-md border px-3 py-2 text-[12.5px] shadow-pop ${
            msg.ok
              ? "border-transparent bg-low-soft text-ok"
              : "border-transparent bg-high-soft text-risk-high"
          }`}
        >
          {msg.text}
        </div>
      )}

      {/* no usual recipient configured: ask for one */}
      {!defaultTo && open && (
        <div className="absolute right-0 top-full z-40 mt-2 w-72 animate-pop-in rounded-lg border border-line bg-surface p-3 shadow-pop">
          <div className="section-label mb-1.5">Email this brief</div>
          <input
            type="email"
            value={to}
            onChange={(e) => setTo(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && to.trim() && !busy && send(to.trim())}
            placeholder="sho@example.gov.in"
            className="w-full rounded-lg border border-line bg-surface px-3 py-2 text-sm text-ink outline-none transition placeholder:text-dim focus:border-core"
            autoFocus
          />
          <div className="mt-2 flex items-center justify-between gap-2">
            {msg ? (
              <span className={`text-[11px] ${msg.ok ? "text-ok" : "text-risk-high"}`}>
                {msg.text}
              </span>
            ) : (
              <span className="text-[11px] text-dim">via Resend</span>
            )}
            <button
              onClick={() => send(to.trim())}
              disabled={busy || !to.trim()}
              className="btn-primary px-3 py-1.5 text-[13px]"
            >
              {busy ? "Sending…" : "Send"}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
